name: butceakintisi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Routing
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0   
  google_fonts: ^6.1.0
  gap: ^3.0.0
  fl_chart: ^1.1.1
  # State Management (The Brains)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Database (The Vault)
  path_provider: ^2.1.2      # To find where to save the DB
  shared_preferences: ^2.5.4

  # Utilities
  intl: ^0.19.0           # For formatting Currency & Dates

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # The "Construction Crew" (Code Generators)
  build_runner: ^2.4.9      # The manager that runs the generators
  riverpod_generator: ^2.3.5 # Writes your provider code
 
flutter:
  uses-material-design: true